"""empty message

Revision ID: 34244a3320fc
Revises: 
Create Date: 2023-04-17 22:11:12.400628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34244a3320fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('surname', sa.String(length=1000), nullable=True),
    sa.Column('pseudo', sa.String(length=1000), nullable=True),
    sa.Column('date_n', sa.String(length=1000), nullable=True),
    sa.Column('phone', sa.String(length=1000), nullable=True),
    sa.Column('condition', sa.String(length=1000), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('solde', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('compte__quickcash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_compt', sa.String(length=1000), nullable=True),
    sa.Column('solde', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_game', sa.String(length=1000), nullable=True),
    sa.Column('paid', sa.Integer(), nullable=True),
    sa.Column('message', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Text(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tmp_game',
    sa.Column('tmp_id', sa.Integer(), nullable=False),
    sa.Column('tmp_id_game', sa.String(length=1000), nullable=True),
    sa.Column('tmp_mise', sa.Integer(), nullable=True),
    sa.Column('tmp_message', sa.Integer(), nullable=True),
    sa.Column('tmp_user_id', sa.Integer(), nullable=True),
    sa.Column('tmp_statut', sa.Text(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tmp_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('tmp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmp_game')
    op.drop_table('game')
    op.drop_table('compte__quickcash')
    op.drop_table('user')
    # ### end Alembic commands ###
